### ISSUE TITLE
Add config option, so that only the player using the Light Block Tool can see particles

### ISSUE THREAD

**Issue by Toseflo** [ItsAZZA/LightBlockZ#1]
When a player uses the Light Block Tool, every player around him can see the particles. It would be great to have a config option, so that only the player who uses the tool can see the particles.

Something unrelated: I was wondering why the file size is 1.8 MB. This seems very large compared to other plugins and maybe there is a way for you to reduce the size.

**Comment by ItsAZZA** [comment]
Thanks for the suggestion! Yes, the particles do show to everyone. Didn't really even think it that far. I shall look into making them per player 😄

The plugin is made in Kotlin so I have to include the Kotlin libraries in the plugin jar which contributes to its size. I think this is more convenient than have the user to download an additional plugin (library) to their server. The size doesn't affect performance at all and making it smaller only moves the file to somewhere else on the disk instead of being in the plugin jar itself.
